export const DATA = [
  {
    name: "Anne with an E",
    logo: "/images/ann/ann-logo.png",
    mainImage: "/images/ann/ann-main.jpg",
    keyImage: "/images/ann/ann-key.jpg",
    year: 2017,
    limitAge: "13+",
    rating: "IMDb 8.7",
    duration: "3 Seasons",
    serial: true,
    category: ["films", "popular"],
    description:
      'A plucky orphan whose passions run deep finds an unlikely home with a spinster and her soft-spoken bachelor brother. Based on "Anne of Green Gables".',
    link: "S5qJXYNNINo",
    episodes: [
      [
        "/images/ann/1/ann-1.jpg",
        "/images/ann/1/ann-2.jpg",
        "/images/ann/1/ann-3.jpg",
        "/images/ann/1/ann-4.jpg",
        "/images/ann/1/ann-5.jpg",
        "/images/ann/1/ann-6.jpg",
        "/images/ann/1/ann-7.jpg",
      ],
      [
        "/images/ann/2/ann-1.jpg",
        "/images/ann/2/ann-2.jpg",
        "/images/ann/2/ann-3.jpg",
        "/images/ann/2/ann-4.jpg",
        "/images/ann/2/ann-5.jpg",
        "/images/ann/2/ann-6.jpg",
        "/images/ann/2/ann-7.jpg",
        "/images/ann/2/ann-8.jpg",
        "/images/ann/2/ann-9.jpg",
        "/images/ann/2/ann-10.jpg",
      ],
      [
        "/images/ann/3/ann-1.jpg",
        "/images/ann/3/ann-2.jpg",
        "/images/ann/3/ann-3.jpg",
        "/images/ann/3/ann-4.jpg",
        "/images/ann/3/ann-5.jpg",
        "/images/ann/3/ann-6.jpg",
        "/images/ann/3/ann-7.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. Your Will Shall Decide Your Destiny",
        "2. I Am No Bird, and No Net Ensnares Me",
        "3. But What Is So Headstrong as Youth?",
        "4. An Inward Treasure Born",
        "5. Tightly Knotted to a Similar String",
        "6. Remorse Is the Poison of Life",
        "7. Wherever You Are Is My Home",
      ],
      [
        "1. Youth Is the Season of Hope",
        "2. Signs Are Small Measurable Things, But Interpretations Are Illimitable",
        "3. The True Seeing Is Within",
        "4. The Painful Eagerness of Unfed Hope",
        "5. The Determining Acts of Her Life",
        "6. I Protest Against Any Absolute Conclusion",
        "7. Memory Has as Many Moods as the Temper",
        "8. Struggling Against the Perception of Facts",
        "9. What We Have Been Makes Us What We Are",
        "10. The Growing Good of the World",
      ],
      [
        "1. A Secret Which I Desired to Divine",
        "2. There Is Something at Work in My Soul Which I Do Not Understand",
        "3. What Can Stop the Determined Heart",
        "4. A Hope of Meeting You in Another World",
        "5. I Am Fearless and Therefore Powerful",
        "6. The Summit of My Desires",
        "7. A Strong Effort of the Spirit of Good",
        "8. Great and Sudden Change",
        "9. A Dense and Frightful Darkness",
        "10. The Better Feelings of My Heart",
      ],
    ],
    genres:
      "Canadian, TV Shows Based on Books, Family Watch Together TV, Teen TV Shows, Period Pieces, TV Dramas",
    starring: ["Amybeth McNulty", "Geraldine James", "R.H. Thomson"],
    creators: "Moira Walley-Beckett",
  },

  {
    name: "The Boss Baby: Back in the Crib",
    logo: "/images/boss-baby/boss-baby-logo.png",
    mainImage: "/images/boss-baby/boss-baby-main.jpg",
    keyImage: "/images/boss-baby/boss-baby-key-image.jpg",
    year: 2022,
    limitAge: "7+",
    rating: "IMDb 6.2",
    duration: "1 Season",
    serial: true,
    category: ["cartoons", "popular"],
    description:
      "Framed for a corporate crime, an adult Ted Templeton turns back into the Boss Baby to live undercover with his brother, Tim, posing as one of his kids.",
    link: "6Au9wukj7pY",
    episodes: [
      [
        "/images/boss-baby/boss-baby-1.jpg",
        "/images/boss-baby/boss-baby-2.jpg",
        "/images/boss-baby/boss-baby-3.jpg",
        "/images/boss-baby/boss-baby-4.jpg",
        "/images/boss-baby/boss-baby-5.jpg",
        "/images/boss-baby/boss-baby-6.jpg",
        "/images/boss-baby/boss-baby-7.jpg",
        "/images/boss-baby/boss-baby-8.jpg",
        "/images/boss-baby/boss-baby-9.jpg",
        "/images/boss-baby/boss-baby-10.jpg",
        "/images/boss-baby/boss-baby-11.jpg",
        "/images/boss-baby/boss-baby-12.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. The Business Boss: Back in Baby",
        "2. The Stroll",
        "3. Potty Mouth",
        "4. Imaginary Friends",
        "5. Turf War",
        "6. Trading Up",
        "7. War of the Cheeks",
        "8. Techy Tykes",
        "9. Birthday Blues",
        "10. Sitting Ducks",
        "11. The Big Dumpling",
        "12. The Great Medieval London Fire",
      ],
    ],
    genres:
      "Kids' TV, TV Cartoons, TV Shows Based on Books, Family Watch Together TV, TV Comedies",
    starring: ["JP Karliak", "Mary Faber", "Nicole Byer"],
  },
  {
    name: "Bridgerton",
    logo: "/images/bridgerton/bridgerton-logo.png",
    mainImage: "/images/bridgerton/bridgerton-main.jpg",
    keyImage: "/images/bridgerton/bridgerton-key-image.jpg",
    year: 2020,
    limitAge: "16+",
    rating: "IMDb 7.4",
    duration: "2 Seasons",
    serial: true,
    category: ["films", "popular"],
    description:
      "The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society. Inspired by Julia Quinn's bestselling novels.",
    link: "gpv7ayf_tyE",
    episodes: [
      [
        "/images/bridgerton/bridgerton-1-1.jpg",
        "/images/bridgerton/bridgerton-1-2.jpg",
        "/images/bridgerton/bridgerton-1-3.jpg",
        "/images/bridgerton/bridgerton-1-4.jpg",
        "/images/bridgerton/bridgerton-1-5.jpg",
        "/images/bridgerton/bridgerton-1-6.jpg",
        "/images/bridgerton/bridgerton-1-7.jpg",
        "/images/bridgerton/bridgerton-1-8.jpg",
      ],
      [
        "/images/bridgerton/bridgerton-2-1.jpg",
        "/images/bridgerton/bridgerton-2-2.jpg",
        "/images/bridgerton/bridgerton-2-3.jpg",
        "/images/bridgerton/bridgerton-2-4.jpg",
        "/images/bridgerton/bridgerton-2-5.jpg",
        "/images/bridgerton/bridgerton-2-6.jpg",
        "/images/bridgerton/bridgerton-2-7.jpg",
        "/images/bridgerton/bridgerton-2-8.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. Diamond of the First Water",
        "2. Shock and Delight",
        "3. Art of the Swoon",
        "4. An Affair of Honor",
        "5. The Duke and I",
        "6. Swish",
        "7. Oceans Apart",
        "8. After the Rain",
      ],
      [
        "1. Capital R Rake",
        "2. Off to the Races",
        "3. A Bee in Your Bonnet",
        "4. Victory",
        "5. An Unthinkable Fate",
        "6. The Choice",
        "7. Harmony",
        "8. The Viscount Who Loved Me",
      ],
    ],
    genres:
      "Romantic TV Dramas, TV Shows Based on Books, Period Pieces, TV Dramas, US TV Shows",
    starring: ["Adjoa Andoh", "Julie Andrews", "Lorraine Ashbourne"],
    creators: "Chris Van Dusen",
  },
  {
    name: "The Croods",
    logo: "/images/croods/croods-logo.png",
    mainImage: "/images/croods/croods-main.jpg",
    keyImage: "/images/croods/croods-key.jpg",
    year: 2013,
    limitAge: "7+",
    rating: "IMDb 7.2",
    duration: "1h 38m",
    serial: false,
    category: ["cartoons", "popular"],
    description:
      "When an earthquake obliterates their cave, an unworldly prehistoric family is forced to journey through unfamiliar terrain in search of a new home.",
    link: "4fVCKy69zUY",
    genres: "Family Movies, Kids & Family Movies, Comedies",
    starring: ["Nicolas Cage", "Emma Stone", "Ryan Reynolds"],
  },

  {
    name: "Money Heist",
    logo: "/images/money-heist/money-heist-logo.png",
    mainImage: "/images/money-heist/money-heist-main.jpg",
    keyImage: "/images/money-heist/money-heist-key.jpg",
    year: 2017,
    limitAge: "16+",
    rating: "IMDb 8.2",
    duration: "5 Seasons",
    serial: true,
    category: ["films", "popular"],
    description:
      "Eight thieves take hostages and lock themselves in the Royal Mint of Spain as a criminal mastermind manipulates the police to carry out his plan.",
    link: "_InqQJRqGW4",
    episodes: [
      [
        "/images/money-heist/1/money-heist-1.jpg",
        "/images/money-heist/1/money-heist-2.jpg",
        "/images/money-heist/1/money-heist-3.jpg",
        "/images/money-heist/1/money-heist-4.jpg",
        "/images/money-heist/1/money-heist-5.jpg",
        "/images/money-heist/1/money-heist-6.jpg",
        "/images/money-heist/1/money-heist-7.jpg",
        "/images/money-heist/1/money-heist-8.jpg",
        "/images/money-heist/1/money-heist-9.jpg",
        "/images/money-heist/1/money-heist-10.jpg",
        "/images/money-heist/1/money-heist-11.jpg",
        "/images/money-heist/1/money-heist-12.jpg",
        "/images/money-heist/1/money-heist-13.jpg",
      ],
      [
        "/images/money-heist/2/money-heist-1.jpg",
        "/images/money-heist/2/money-heist-2.jpg",
        "/images/money-heist/2/money-heist-4.jpg",
        "/images/money-heist/2/money-heist-3.jpg",
        "/images/money-heist/2/money-heist-5.jpg",
        "/images/money-heist/2/money-heist-6.jpg",
        "/images/money-heist/2/money-heist-7.jpg",
        "/images/money-heist/2/money-heist-8.jpg",
        "/images/money-heist/2/money-heist-9.jpg",
      ],
      [
        "/images/money-heist/3/money-heist-1.jpg",
        "/images/money-heist/3/money-heist-2.jpg",
        "/images/money-heist/3/money-heist-3.jpg",
        "/images/money-heist/3/money-heist-4.jpg",
        "/images/money-heist/3/money-heist-5.jpg",
        "/images/money-heist/3/money-heist-6.jpg",
        "/images/money-heist/3/money-heist-7.jpg",
        "/images/money-heist/3/money-heist-8.jpg",
      ],
      [
        "/images/money-heist/4/money-heist-1.jpg",
        "/images/money-heist/4/money-heist-2.jpg",
        "/images/money-heist/4/money-heist-3.jpg",
        "/images/money-heist/4/money-heist-4.jpg",
        "/images/money-heist/4/money-heist-5.jpg",
        "/images/money-heist/4/money-heist-6.jpg",
        "/images/money-heist/4/money-heist-7.jpg",
        "/images/money-heist/4/money-heist-8.jpg",
      ],
      [
        "/images/money-heist/1/money-heist-1.jpg",
        "/images/money-heist/1/money-heist-2.jpg",
        "/images/money-heist/1/money-heist-3.jpg",
        "/images/money-heist/1/money-heist-4.jpg",
        "/images/money-heist/1/money-heist-5.jpg",
        "/images/money-heist/1/money-heist-6.jpg",
        "/images/money-heist/1/money-heist-7.jpg",
        "/images/money-heist/1/money-heist-8.jpg",
        "/images/money-heist/1/money-heist-9.jpg",
        "/images/money-heist/1/money-heist-10.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. Episode 1",
        "2. Episode 2",
        "3. Episode 3",
        "4. Episode 4",
        "5. Episode 5",
        "6. Episode 6",
        "7. Episode 7",
        "8. Episode 8",
        "9. Episode 9",
        "10. Episode 10",
        "11. Episode 11",
        "12. Episode 12",
        "13. Episode 13",
      ],
      [
        "1. Episode 1",
        "2. Episode 2",
        "3. Episode 3",
        "4. Episode 4",
        "5. Episode 5",
        "6. Episode 6",
        "7. Episode 7",
        "8. Episode 8",
        "9. Episode 9",
      ],
      [
        "1. We're Back",
        "2. Aikido",
        "3. 48 Meters Underground",
        "4. It's Dolphin Time",
        "5. Boom, Boom, Ciao",
        "6. Everything Seemed Insignificant",
        "7. A Quick Vacation",
        "8. Astray",
      ],
      [
        "1. Game Over",
        "2. Berlin's Wedding",
        "3. Anatomy Lesson",
        "4. Pasodoble",
        "5. 5 Minutes Earlier",
        "6. TKO",
        "7. Strike the Tent",
        "8. The Paris Plan",
      ],
      [
        "1. The End of the Road",
        "2. Do You Believe in Reincarnation?",
        "3. Welcome to the Spectacle of Life",
        "4. Your Place in Heaven",
        "5. Live Many Lives",
        "6. Escape Valve",
        "7. Wishful Thinking",
        "8. The Elegance Theory",
        "9. Pillow Talk",
        "10. A Family Tradition",
      ],
    ],
    genres: "Crime TV Shows, Spanish, TV Thrillers",
    starring: ["Úrsula Corberó", " Álvaro Morte", "Itziar Ituño"],
    creators: "Álex Pina",
  },
  {
    name: "The Secret Life of Pets",
    logo: "/images/secret-life-pets/secret-life-pets-logo.png",
    mainImage: "/images/secret-life-pets/secret-life-pets-main.jpg",
    keyImage: "/images/secret-life-pets/secret-life-pets-key.jpg",
    year: 2016,
    limitAge: "All",
    rating: "IMDb 6.5",
    duration: "1h 26m",
    serial: false,
    category: ["cartoons", "popular"],
    description:
      "After ending up in the outside world, two squabbling pet dogs find common ground against a gang of angry animals preparing an attack on humans.",
    link: "i-80SGWfEjM",
    genres: "Family Movies, Kids & Family Movies, Comedies",
    starring: ["Louis C.K", "Eric Stonestreet", "Kevin Hart"],
  },
  {
    name: "The Queen's Gambit",
    logo: "/images/queens-gambit/queens-gambit-logo.png",
    mainImage: "/images/queens-gambit/queens-gambit-main.jpg",
    keyImage: "/images/queens-gambit/queens-gambit-key-image.jpg",
    year: 2020,
    limitAge: "16+",
    rating: "IMDb 8.6",
    duration: "1 Season",
    serial: true,
    category: ["films", "popular"],
    description:
      "In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.",
    link: "FU854_5itOk",
    episodes: [
      [
        "/images/queens-gambit/queens-gambit-1.jpg",
        "/images/queens-gambit/queens-gambit-2.jpg",
        "/images/queens-gambit/queens-gambit-3.jpg",
        "/images/queens-gambit/queens-gambit-4.jpg",
        "/images/queens-gambit/queens-gambit-5.jpg",
        "/images/queens-gambit/queens-gambit-6.jpg",
        "/images/queens-gambit/queens-gambit-7.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. Openings",
        "2. Exchanges",
        "3. Doubled Pawns",
        "4. Middle Game",
        "5. Fork",
        "6. Adjournment",
        "7. End Game",
      ],
    ],
    genres:
      "TV Shows Based on Books, Social Issue TV Dramas, TV Dramas, US TV Shows",
    starring: ["Anya Taylor-Joy", "Bill Camp", "Marielle Heller"],

    creators: "Scott Frank, Allan Scott",
  },
  {
    name: "Kung Fu Panda: The Dragon Knight",
    logo: "/images/kung-fu-panda/kung-fu-panda-logo.png",
    mainImage: "/images/kung-fu-panda/kung-fu-panda-main.jpg",
    keyImage: "/images/kung-fu-panda/kung-fu-panda-key.jpg",
    year: 2022,
    limitAge: "7+",
    rating: "IMDb 5.9",
    duration: "1 Season",
    serial: true,
    category: ["cartoons", "popular"],
    description:
      "Legendary warrior Po teams up with an elite English knight on a global quest to rescue magical weapons, restore his reputation — and save the world!",
    link: "MYy7oGQiSqI",
    episodes: [
      [
        "/images/kung-fu-panda/kung-fu-panda-1.jpg",
        "/images/kung-fu-panda/kung-fu-panda-2.jpg",
        "/images/kung-fu-panda/kung-fu-panda-3.jpg",
        "/images/kung-fu-panda/kung-fu-panda-4.jpg",
        "/images/kung-fu-panda/kung-fu-panda-5.jpg",
        "/images/kung-fu-panda/kung-fu-panda-6.jpg",
        "/images/kung-fu-panda/kung-fu-panda-7.jpg",
        "/images/kung-fu-panda/kung-fu-panda-8.jpg",
        "/images/kung-fu-panda/kung-fu-panda-9.jpg",
        "/images/kung-fu-panda/kung-fu-panda-10.jpg",
        "/images/kung-fu-panda/kung-fu-panda-11.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. A Cause for the Paws",
        "2. The Knight's Code",
        "3. The Lotus",
        "4. The Legend of Master Longtooth",
        "5. The Gateway to the Desert",
        "6. The Lost City",
        "7. The Last Guardian",
        "8.  A Thread in the Dark",
        "9. Slow Boat to England",
        "10. The Knight's Fall Part 1",
        "11. The Knight's Fall Part 2",
      ],
    ],
    genres: "Kids' TV, TV Cartoons, TV Comedies",
    starring: ["Jack Black", "Rita Ora", "James Hong"],
  },

  {
    name: "The Last Dance",
    logo: "/images/last-dance/last-dance-logo.png",
    mainImage: "/images/last-dance/last-dance-main.jpg",
    keyImage: "/images/last-dance/last-dance-key.jpg",
    year: 2020,
    limitAge: "16+",
    rating: "IMDb 9.1",
    duration: "1 Season",
    serial: true,
    category: ["films", "popular"],
    description:
      "This docuseries chronicles the rise of superstar Michael Jordan and the 1990s Chicago Bulls, with unaired footage from an unforgettable 1997-98 season.",
    link: "JQk2hJs2ToA",
    episodes: [
      [
        "/images/last-dance/last-dance-1.jpg",
        "/images/last-dance/last-dance-2.jpg",
        "/images/last-dance/last-dance-3.jpg",
        "/images/last-dance/last-dance-4.jpg",
        "/images/last-dance/last-dance-5.jpg",
        "/images/last-dance/last-dance-6.jpg",
        "/images/last-dance/last-dance-7.jpg",
        "/images/last-dance/last-dance-8.jpg",
        "/images/last-dance/last-dance-9.jpg",
        "/images/last-dance/last-dance-10.jpg",
      ],
    ],
    episodesTitle: [
      [
        "1. Episode I",
        "2. Episode II",
        "3. Episode III",
        "4. Episode IV",
        "5. Episode V",
        "6. Episode VI",
        "7. Episode VII",
        "8. Episode VIII",
        "9. Episode IX",
        "10. Episode X",
      ],
    ],
    genres: "Social & Cultural Docs, Docuseries, US TV Shows",
    starring: ["Michael Jordan", "Scottie Pippen", "Dennis Rodman"],
  },
  {
    name: "How to Train Your Dragon",
    logo: "/images/dragon/dragon-logo.png",
    mainImage: "/images/dragon/dragon-main.jpg",
    keyImage: "/images/dragon/dragon-key.jpg",
    year: 2010,
    limitAge: "7+",
    rating: "IMDb 8.1",
    duration: "1h 40m",
    serial: false,
    category: ["cartoons", "popular"],
    description:
      "Shy teen Hiccup must prove to his father and his village that he can still be a viking warrior — even if he'd rather befriend a dragon than slay one.",
    link: "oKiYuIsPxYk",
    genres: "Family Movies, Movies Based on Books, Kids & Family Movies",
    starring: ["Jay Baruchel", "Gerard Butler", "Craig Ferguson"],
  },
  {
    name: "Enola Holmes 2",
    logo: "/images/enola-holmes/enola-holmes-logo.jpg",
    mainImage: "/images/enola-holmes/enola-holmes-main.jpg",
    keyImage: "/images/enola-holmes/enola-holmes-key.jpg",
    year: 2022,
    limitAge: "13+",
    rating: "IMDb 6.8",
    duration: "2h 10m",
    serial: false,
    category: ["films", "popular"],
    description:
      "Enola takes on her first official case as a detective, but to solve the mystery of a missing girl, she'll need help from friends — and brother Sherlock.",
    link: "KKXNmYoPkx0",
    genres:
      "Mysteries, Social Issue Dramas, Family Movies, Period Pieces, Movies Based on Books, Action & Adventure, Dramas",
    starring: ["Millie Bobby Brown", "Henry Cavill", "David Thewlis"],
  },

  {
    name: "Madagascar 3: Europe's Most Wanted",
    logo: "/images/madagascar/madagascar-logo.png",
    mainImage: "/images/madagascar/madagascar-main.jpg",
    keyImage: "/images/madagascar/madagascar-key.jpg",
    year: 2012,
    limitAge: "7+",
    rating: "IMDb 6.8",
    duration: "1h 35m",
    serial: false,
    category: ["cartoons", "popular"],
    description:
      "Next stop: New York! But to get back home, Alex and friends must hitch a ride with a traveling European circus and evade an evil animal-control officer.",
    link: "PlkWVkpP59U",
    genres: "Family Movies, Kids & Family Movies, Comedies",
    starring: ["Ben Stiller", "Chris Rock", "David Schwimmer"],
  },
];
